services:
  - type: web
    name: atm-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: CLOUDANT_API_KEY
        sync: false
      - key: CLOUDANT_USERNAME
        sync: false
      - key: CLOUDANT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
